# Use container-based infrastructure
sudo: false

language: scala
scala: 2.11.7
jdk: oraclejdk8

before_script:
  - npm set progress=false
  - npm install -g --prefix node_modules/ gitbook-cli
  - export PATH="$PATH:$PWD/node_modules/bin/"
  - gitbook install

script:
  - sbt ++$TRAVIS_SCALA_VERSION reformat-code-check test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

before_deploy:
  - gitbook build

deploy:
  provider: script
  script: devops/deploy-site.sh
  skip_cleanup: true
  on:
    all_branches: true

#    branch: master
#    condition: $TRAVIS_PULL_REQUEST = false

# These directories are cached at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.gitbook
    - node_modules/

env:
  global:
    secure: "DTM8LplUqjcBsRdvKv171K7I8V0kdD0Qsf/nIvuDsWfXbES4l1yqORDC25iHaZsld7lFfpyQ8bAWMUF8tWmwKyOc6h4IDqVVv8L3+U3aACf3NCe+XEdEP1uG/v2CqcaCUI9d6wD6e1VwGE7ebrsyMZkPoft2UGqhSpXHm29S9pg8LYkLcPcWzpBavaNT2iwHFmIhxuDbIqQZOhBtm6HPh7bN6jolwu+wQIvLM4Zlh1i+wgif0gVwhSU+mIDOBJKblBu+w67Tjie8d5CLmeZclOi5LrmphDgxqmouRvjWfm7HlLNJqYn19ocyWWd4n6mNL2ho9Vl4O+Z5kH3QOmF1NY/kG+YuLWRZ6h3QEXSfBuTtGGYs0KtRC5Frt0K3hJhcv9b+VTSjIDyQCv8skOTjPNUUMJcqxW+K6ySbmJNMl1crdmW0u2b9ngdzIl3o48WHkEAPhF5PkpFGZH5+8FjdWIz356SUaXJvFOh0d6Y+qsKd9ubcYyvUuCzdDUEjUylF4dZUoWVY75I+7xbUsvc23A8SfVy1KTiR3Ij1+40PcIw/zvApZw3DWcl47kqpv4N834LhhdG73oD08cgT5ta+/sifUIDQbU05elp634Yk9OOD0XlcMM3G6zdO4XQmYQ48rpXtZsAieunyVO0e5PeSUlsp08K5R8sCi//EereYRcs="
